import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import { useState } from 'react';
import Head from 'next/head';
import { Input } from '../src/components/Input';
import { Button } from '../src/components/Button';
import styles from '../styles/CreateAccount.module.scss';

const CreateAccount: NextPage = () => {

  const [regType, changeType] = useState(false);
  const router = useRouter();
  const style = styles.regType_option__selected;

  return (
    <section className={styles.wrapper}>
      <Head>
        <title>Rocketseat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <i className={`${styles.header_icon} + bi bi-arrow-left`} onClick={() => router.back()}></i>
      </header>

      <main className={styles.main}>
        <div className={styles.regType}>
          <strong className={styles.regType_option + " " + (regType == false ? style : "")} onClick={() => changeType(false)}>Aluno</strong>
          <strong className={styles.regType_option + " " + (regType == true ? style : "")} onClick={() => changeType(true)}>Empresa</strong>
        </div>
        {
          regType
            ?
            <form className={styles.form} action="">
              <h2 className={styles.form_title}>Cadastro de empresa</h2>
              <Input type="text" icon='bi bi-file-earmark' placeholder='CNPJ' required />
              <Input type="text" icon='bi bi-building' placeholder='Nome da sua empresa' required />
              <Input type="email" icon="bi bi-envelope-fill" placeholder='Digite seu e-mail' required />
              <p className={styles.form_terms}>Ao se registrar, voce aceita nossos <strong>termos de uso</strong> e nossa <strong>política de privacidade</strong>.</p>
              <Button onClick={() => router.push("login")}>CADASTRAR</Button>
            </form>
            :
            <form className={styles.form} action="">
              <h2 className={styles.form_title}>Crie sua Conta</h2>
              <Input type="email" icon='bi bi-envelope-fill' placeholder='Digite seu e-mail' required />
              <Input type="text" icon='bi bi-person-fill' placeholder='Seu nome' required />
              <Input type="password" icon="bi bi-lock-fill" placeholder='Digite sua senha' required />
              <Input type="password" icon="bi bi-lock-fill" placeholder='Confirme sua senha' required />
              <p className={styles.form_terms}>Ao se registrar, voce aceita nossos <strong>termos de uso</strong> e nossa <strong>política de privacidade</strong>.</p>
              <Button onClick={() => router.push("login")}>CADASTRAR</Button>
            </form>
        }

      </main>
    </section>
  )
}

export default CreateAccount;