import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/createAccount.module.scss';

const CreateAccount: NextPage = () => {
  return (
    <section>
      <Head>
        <title>Rocketseat App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </section>
  )
}

export default CreateAccount;